# Generated by Django 5.0.6 on 2026-02-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=300)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('comentario', models.TextField(blank=True, default='')),
                ('manana_lunes', models.BooleanField(default=False, verbose_name='Mañana Lunes')),
                ('manana_martes', models.BooleanField(default=False, verbose_name='Mañana Martes')),
                ('manana_miercoles', models.BooleanField(default=False, verbose_name='Mañana Miércoles')),
                ('manana_jueves', models.BooleanField(default=False, verbose_name='Mañana Jueves')),
                ('manana_viernes', models.BooleanField(default=False, verbose_name='Mañana Viernes')),
                ('manana_sabado', models.BooleanField(default=False, verbose_name='Mañana Sábado')),
                ('manana_domingo', models.BooleanField(default=False, verbose_name='Mañana Domingo')),
                ('tarde_lunes', models.BooleanField(default=False, verbose_name='Tarde Lunes')),
                ('tarde_martes', models.BooleanField(default=False, verbose_name='Tarde Martes')),
                ('tarde_miercoles', models.BooleanField(default=False, verbose_name='Tarde Miércoles')),
                ('tarde_jueves', models.BooleanField(default=False, verbose_name='Tarde Jueves')),
                ('tarde_viernes', models.BooleanField(default=False, verbose_name='Tarde Viernes')),
                ('tarde_sabado', models.BooleanField(default=False, verbose_name='Tarde Sábado')),
                ('tarde_domingo', models.BooleanField(default=False, verbose_name='Tarde Domingo')),
                ('mensaje_enviado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
                'ordering': ['nombre'],
            },
        ),
    ]
