# Generated by Django 5.0.6 on 2026-04-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='cartas_tarde',
            field=models.BooleanField(default=False, verbose_name='Disponible para cartas en la tarde'),
        ),
    ]
