# Generated by Django 5.0.6 on 2026-04-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_casa_cartas_tarde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='cartas_tarde',
        ),
        migrations.AddField(
            model_name='casa',
            name='cartas_tarde_domingo',
            field=models.BooleanField(default=False, verbose_name='Cartas Tarde Domingo'),
        ),
        migrations.AddField(
            model_name='casa',
            name='cartas_tarde_jueves',
            field=models.BooleanField(default=False, verbose_name='Cartas Tarde Jueves'),
        ),
        migrations.AddField(
            model_name='casa',
            name='cartas_tarde_lunes',
            field=models.BooleanField(default=False, verbose_name='Cartas Tarde Lunes'),
        ),
        migrations.AddField(
            model_name='casa',
            name='cartas_tarde_martes',
            field=models.BooleanField(default=False, verbose_name='Cartas Tarde Martes'),
        ),
        migrations.AddField(
            model_name='casa',
            name='cartas_tarde_miercoles',
            field=models.BooleanField(default=False, verbose_name='Cartas Tarde Miércoles'),
        ),
        migrations.AddField(
            model_name='casa',
            name='cartas_tarde_sabado',
            field=models.BooleanField(default=False, verbose_name='Cartas Tarde Sábado'),
        ),
        migrations.AddField(
            model_name='casa',
            name='cartas_tarde_viernes',
            field=models.BooleanField(default=False, verbose_name='Cartas Tarde Viernes'),
        ),
    ]
